name: bip32_defichain
description: A BIP32 (https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki) compatible library for Flutter writing by Dart. Fork (https://github.com/DeFiCh-WalletApp/bip32-dart)
version: 2.0.0
homepage: https://github.com/DeFiCh-WalletApp/bip32-dart

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  pointycastle: ^2.0.1
  hex: ^0.2.0
  bs58check_dart: ^2.0.0+1

dev_dependencies:
  test: ^1.0.0
